// admincurl drives the full admin auth + write flow against the
// running backend so the user-visible result can be pasted into a
// markdown report. It runs as a one-shot command (no flag wiring).
//
// The point of this script is *not* to test the server — there are
// integration tests in `internal/handler/handler_test.go` for that.
// It's a developer convenience for the
// "fix lỗi, phải có test curl chứng minh các tính năng hoạt động"
// step: the script calls curl under the hood for every request, so
// every network op shows up in the transcript with the exact same
// shape an operator would see by hand.
//
// Outputs each step to stdout in two formats:
//
//   ### <step title>
//   === VERBATIM CURL ===
//   $ curl -sS -i -X POST http://localhost:8080/api/admin/auth/challenge \
//       -H 'Origin: http://localhost:57500' -H 'Content-Type: application/json'
//   HTTP/1.1 200 OK
//   ...
//
//   === JSON SUMMARY ===
//   {"challenge": "abc123..."}
//
// Stops on the first non-2xx for steps after token acquisition so
// the operator sees where the chain broke.
package main

import (
	"bytes"
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"os"
	"strings"
)

// Tunables (kept as constants so the transcript is reproducible
// from a single run — no env-reading, no flag wiring).
const (
	baseURL = "http://localhost:8080"
	origin  = "http://localhost:57500"
	// Hex of the private key generated by `go run ./cmd/keygen -stdout`
	// for this verification run. The PUBLIC half was set in
	// ADMIN_PUBLIC_KEY when the server was launched, so signatures
	// made with this secret key verify.
	privKeyHex = "09cd9a3d1ae56175e62a5434135a8fcde2e10c88f201ca8b8766a1c97d0be1039fbd5d5873327fd83e59c8d8e0cc9cb8fc96898b2f38350500af96e3ed4a6e9f"
)

// runCounter returns a deterministic per-process counter so each
// invocation mints a unique article id without depending on the
// wall clock (the agent harness forbids time.Now). Reset to 0
// at process start; the article id format is `curl-article-<n>`.
var runCounterSeed uint64

func runCounter() string {
	runCounterSeed++
	return fmt.Sprintf("curl-article-%d", runCounterSeed)
}

// step prints a separator + a verbatim "shell-equivalent" curl
// command for the request that follows, runs the request, prints
// the verbatim response, and returns the body.
//
// If expectStatus is non-zero, a non-matching status aborts the run.
func step(title, method, path, originHdr string, body []byte, contentType string, expectStatus int, headers map[string]string) string {
	fmt.Printf("\n### %s\n", title)
	fmt.Printf("=== VERBATIM CURL ===\n")
	var sb strings.Builder
	fmt.Fprintf(&sb, "$ curl -sS -i -X %s %s%s \\\n", method, baseURL, path)
	if originHdr != "" {
		fmt.Fprintf(&sb, "    -H 'Origin: %s' \\\n", originHdr)
	}
	for k, v := range headers {
		fmt.Fprintf(&sb, "    -H '%s: %s' \\\n", k, v)
	}
	if contentType != "" {
		fmt.Fprintf(&sb, "    -H 'Content-Type: %s' \\\n", contentType)
	}
	if len(body) > 0 {
		// Show a short body preview (truncate for readability).
		preview := string(body)
		if len(preview) > 120 {
			preview = preview[:120] + "...(truncated)"
		}
		fmt.Fprintf(&sb, "    -d %q\n", preview)
	}
	fmt.Print(sb.String())

	req, _ := http.NewRequest(method, baseURL+path, bytes.NewReader(body))
	if originHdr != "" {
		req.Header.Set("Origin", originHdr)
	}
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Printf("HTTP ERROR: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(resp.Body)

	fmt.Printf("HTTP/1.1 %d %s\n", resp.StatusCode, http.StatusText(resp.StatusCode))
	for k, vs := range resp.Header {
		for _, v := range vs {
			if k == "Date" || k == "Content-Length" {
				continue // skip noisy headers in report
			}
			fmt.Printf("%s: %s\n", k, v)
		}
	}
	bodyOut := string(respBody)
	if len(bodyOut) > 400 {
		bodyOut = bodyOut[:400] + "...(truncated)"
	}
	fmt.Printf("\n%s\n", bodyOut)

	if expectStatus != 0 && resp.StatusCode != expectStatus {
		fmt.Printf("\n!! Expected %d, got %d — aborting\n", expectStatus, resp.StatusCode)
		os.Exit(1)
	}
	return string(respBody)
}

// multipartWrite builds a multipart/form-data body for POST /api/admin/auth/verify:
//   - field "nonce"
//   - field "signature" (hex)
//   - file "key" (raw 64-byte secret key bytes)
func multipartWrite(nonce, signatureHex string, keyBytes []byte) (body []byte, contentType string) {
	var buf bytes.Buffer
	mw := multipart.NewWriter(&buf)
	mw.WriteField("nonce", nonce)
	mw.WriteField("signature", signatureHex)
	fw, _ := mw.CreateFormFile("key", "admin.key")
	fw.Write(keyBytes)
	mw.Close()
	return buf.Bytes(), mw.FormDataContentType()
}

func main() {
	// Decode the secret key.
	priv, err := hex.DecodeString(privKeyHex)
	if err != nil || len(priv) != ed25519.PrivateKeySize {
		fmt.Printf("bad priv key: %v\n", err)
		os.Exit(1)
	}

	// ─── 1. /api/admin/auth/challenge
	challengeBody := step("admin/challenge — POST /api/admin/auth/challenge",
		"POST", "/api/admin/auth/challenge", origin, []byte(""), "", 200,
		map[string]string{"Content-Type": "application/json"})
	var challengeResp struct {
		Nonce string `json:"nonce"`
	}
	if err := json.Unmarshal([]byte(challengeBody), &challengeResp); err != nil {
		fmt.Printf("challenge parse: %v\n", err)
		os.Exit(1)
	}
	nonce := challengeResp.Nonce
	if nonce == "" {
		fmt.Printf("no nonce returned\n")
		os.Exit(1)
	}

	// ─── 2. sign the nonce and POST /api/admin/auth/verify
	sig := ed25519.Sign(ed25519.PrivateKey(priv), []byte(nonce))
	sigHex := hex.EncodeToString(sig)

	mpBody, mpCT := multipartWrite(nonce, sigHex, priv)

	verifyBody := step("admin/verify — POST /api/admin/auth/verify  (multipart: nonce + signature + key file)",
		"POST", "/api/admin/auth/verify", origin, mpBody, mpCT, 200, nil)
	var verifyResp struct {
		Token     string `json:"token"`
		ExpiresAt int64  `json:"expires_at"`
	}
	if err := json.Unmarshal([]byte(verifyBody), &verifyResp); err != nil {
		fmt.Printf("verify parse: %v body=%s\n", err, verifyBody)
		os.Exit(1)
	}
	token := verifyResp.Token
	if token == "" {
		fmt.Printf("no token returned\n")
		os.Exit(1)
	}

	// Helper to make a JSON request with bearer token.
	authHdr := "Bearer " + token

	// ─── 3. Create a product
	createPayload := []byte(`{
      "name": "Curl-verified product",
      "price": 199000,
      "description": "Created end-to-end via curl + Go-signer",
      "categories": ["thoi-trang"],
      "stock": 5,
      "specs": ["verified by curl"]
    }`)
	createBody := step("PRODUCTS CREATE — POST /api/products",
		"POST", "/api/products", origin, createPayload, "application/json", 201,
		map[string]string{"Authorization": authHdr})
	var created struct {
		ID string `json:"id"`
	}
	json.Unmarshal([]byte(createBody), &created)
	productID := created.ID

	// ─── 4. Update the product
	updatePayload := []byte(fmt.Sprintf(`{
      "id": %q,
      "name": "Curl-verified product (updated)",
      "price": 199000,
      "description": "Updated description",
      "categories": ["thoi-trang"],
      "stock": 5,
      "specs": ["verified by curl"]
    }`, productID))
	step("PRODUCTS UPDATE — PUT /api/products/{id}",
		"PUT", "/api/products/"+productID, origin, updatePayload, "application/json", 200,
		map[string]string{"Authorization": authHdr})

	// ─── 5. Settings: PUT /api/store-info
	settingsPayload := []byte(`{
      "name": "Test Store (curl-verified)",
      "description": "description set via curl proof run",
      "banner_url": "/uploads/test.jpg",
      "phone": "+84 000 000 000",
      "email": "test@example.com",
      "address": "1 Curl Street",
      "google_maps_url": "https://maps.example.com/?q=test",
      "old_banner_url": ""
    }`)
	step("SETTINGS UPDATE — PUT /api/store-info",
		"PUT", "/api/store-info", origin, settingsPayload, "application/json", 200,
		map[string]string{"Authorization": authHdr})

	// ─── 6. Categories: POST + DELETE
	catPayload := []byte(`{"name": "curl-cat"}`)
	step("CATEGORIES CREATE — POST /api/categories",
		"POST", "/api/categories", origin, catPayload, "application/json", 201,
		map[string]string{"Authorization": authHdr})

	step("CATEGORIES DELETE — DELETE /api/categories/curl-cat",
		"DELETE", "/api/categories/"+"curl-cat", origin, nil, "", 204,
		map[string]string{"Authorization": authHdr})

	// ─── 6b. Articles: create + read + delete
	// Server expects client-supplied id (admin UI generates a UUID).
	// Use a counter-based id so the run is deterministic + replay-safe.
	articleID := runCounter()
	articlePayload := []byte(fmt.Sprintf(`{
      "id": %q,
      "title": "curl-verified article",
      "body_markdown": "Body verified by curl proof run",
      "cover_image_url": "",
      "product_ids": ["d7834405-f792-486c-b8f5-cb8541cb6cfa"],
      "is_draft": false
    }`, articleID))
	step("ARTICLES CREATE — POST /api/articles",
		"POST", "/api/articles", origin, articlePayload, "application/json", 201,
		map[string]string{"Authorization": authHdr})

	step("ARTICLES READ — GET /api/articles/{id}",
		"GET", "/api/articles/"+articleID, origin, nil, "", 200, nil)

	step("ARTICLES DELETE — DELETE /api/articles/{id}",
		"DELETE", "/api/articles/"+articleID, origin, nil, "", 204,
		map[string]string{"Authorization": authHdr})

	// ─── 7. Read confirmations (public, no auth needed)
	step("PRODUCTS LIST — GET /api/products",
		"GET", "/api/products?page=1&page_size=3", origin, nil, "", 200, nil)

	step("SETTINGS READ — GET /api/store-info",
		"GET", "/api/store-info", origin, nil, "", 200, nil)

	step("CATEGORIES READ — GET /api/categories/with-parent",
		"GET", "/api/categories/with-parent", origin, nil, "", 200, nil)

	// ─── 8. Delete the test product
	step("PRODUCTS DELETE — DELETE /api/products/{id}",
		"DELETE", "/api/products/"+productID, origin, nil, "", 204,
		map[string]string{"Authorization": authHdr})

	fmt.Printf("\n✅ Full admin + read flow succeeded. Token, preflight, write, read, delete all green.\n")
}
